# 01 – Iteration 3: Data Cleaning for Dataset 2 (Repte Consums Anòmals)

This notebook:

1. Loads the **Dataset 2 – "Consum anomalies facturacio complet_anonymized.parquet"**.
2. Saves a **raw CSV copy** in `data/derived/` for easier inspection and debugging.
3. Applies the Iteration 3 basic cleaning rules using `src/cleaning.py`.
4. Saves the **cleaned dataset** (CSV + Parquet) and a JSON summary of cleaning actions in:
   - `iteration_3/results/cleaned/`

The cleaned dataset will be the starting point for:
- `02_iter3_feature_engineering.ipynb`
- `03_iter3_feature_selection.ipynb`
- `04_iter3_dataset_preparation.ipynb`

Imports & paths

In [1]:
# Standard imports
import os
import json
import sys

import pandas as pd

# Make sure Python can find the src/ package
SRC_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", "src"))
if SRC_DIR not in sys.path:
    sys.path.append(SRC_DIR)

from cleaning import load_dataset2, apply_basic_cleaning, save_cleaned_outputs

# Project root = one level above iteration_3/
PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
DERIVED_DIR = os.path.join(DATA_DIR, "derived")

os.makedirs(DERIVED_DIR, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_DIR    :", DATA_DIR)
print("DERIVED_DIR :", DERIVED_DIR)

PROJECT_ROOT: c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D
DATA_DIR    : c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\data
DERIVED_DIR : c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\data\derived

Define dataset paths

In [2]:
# Name of the new Dataset 2 Parquet file
RAW_PARQUET_NAME = "Consum anomalies facturacio complet_anonymized.parquet"

RAW_PARQUET_PATH = os.path.join(DATA_DIR, RAW_PARQUET_NAME)

# CSV copy of the raw dataset for manual inspection
RAW_CSV_DERIVED_PATH = os.path.join(
    DERIVED_DIR, "dataset2_raw_iter3_from_parquet.csv"
)

# Directory for cleaned outputs inside iteration_3
CLEANED_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", "results", "cleaned"))
os.makedirs(CLEANED_DIR, exist_ok=True)

print("RAW_PARQUET_PATH      :", RAW_PARQUET_PATH)
print("RAW_CSV_DERIVED_PATH  :", RAW_CSV_DERIVED_PATH)
print("CLEANED_DIR           :", CLEANED_DIR)

# Quick existence check
if not os.path.exists(RAW_PARQUET_PATH):
    raise FileNotFoundError(f"Raw parquet file not found: {RAW_PARQUET_PATH}")

RAW_PARQUET_PATH      : c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\data\Consum anomalies facturacio complet_anonymized.parquet
RAW_CSV_DERIVED_PATH  : c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\data\derived\dataset2_raw_iter3_from_parquet.csv
CLEANED_DIR           : c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\iteration_3\results\cleaned

Load raw parquet & basic inspection

In [3]:
# 1) Load raw Dataset 2 from Parquet
df_raw = load_dataset2(RAW_PARQUET_PATH)

print("Raw dataset loaded.")
print("Shape:", df_raw.shape)
display(df_raw.head())

Raw dataset loaded.
Shape: (21195970, 9)

,POLISSA_SUBM,CODI_ANOMALIA,START_DATE,END_DATE,US_AIGUA_SUBM,SECCIO_CENSAL,NUMEROSERIECONTADOR,CONSUMO_REAL,FECHA_HORA
0,TZSHLTAPLXX4OYI3,163840,2024-07-08,2024-09-05,DOMÈSTIC,0805601006,P22FA037836K,NaN,2024-01-01
1,FJ2I5K246X6SG3T4,163840,2023-01-26,2023-03-27,DOMÈSTIC,0805602004,P21VA155772I,NaN,2024-01-01
2,MPIXKKMZKJXANKKB,163840,2024-05-07,2024-07-05,DOMÈSTIC,0801507024,I20LA206734D,NaN,2024-01-01
3,LV6FI7TE7BX7NKKE,163840,2023-01-11,2023-03-13,DOMÈSTIC,0820002005,I19LA121835K,NaN,2024-01-01
4,RSSOFEQOC53RL6OD,2,2023-01-16,2023-03-16,DOMÈSTIC,0801906059,P15VA076725J,NaN,2024-01-01

Apply cleaning rules (using cleaning.py)

In [4]:
# 3) Apply Iteration 3 basic cleaning rules
df_clean, cleaning_changes = apply_basic_cleaning(df_raw)

print("Cleaned dataset created.")
print("Cleaned shape:", df_clean.shape)

# Quick sanity checks
display(df_clean.head())
print("\nCleaning summary (first-level keys):")
for k in cleaning_changes.keys():
    print(f"  - {k}: {cleaning_changes[k]}")

Cleaned dataset created.
Cleaned shape: (21195970, 11)

,POLISSA_SUBM,CODI_ANOMALIA,START_DATE,END_DATE,US_AIGUA_SUBM,SECCIO_CENSAL,NUMEROSERIECONTADOR,CONSUMO_REAL,FECHA_HORA,flag_anom_32768,flag_anom_163840
0,TZSHLTAPLXX4OYI3,163840,2024-07-08,2024-09-05,DOMÈSTIC,0805601006,P22FA037836K,NaN,2024-01-01,False,True
1,FJ2I5K246X6SG3T4,163840,2023-01-26,2023-03-27,DOMÈSTIC,0805602004,P21VA155772I,NaN,2024-01-01,False,True
2,MPIXKKMZKJXANKKB,163840,2024-05-07,2024-07-05,DOMÈSTIC,0801507024,I20LA206734D,NaN,2024-01-01,False,True
3,LV6FI7TE7BX7NKKE,163840,2023-01-11,2023-03-13,DOMÈSTIC,0820002005,I19LA121835K,NaN,2024-01-01,False,True
4,RSSOFEQOC53RL6OD,2,2023-01-16,2023-03-16,DOMÈSTIC,0801906059,P15VA076725J,NaN,2024-01-01,False,False

Cleaning summary (first-level keys):
  - anom_32768_count: 6756239
  - anom_163840_count: 9784539
  - dropped_fully_missing_essential: 0

Save cleaned dataset + JSON summary

In [7]:
# 4) Persist cleaned dataset and cleaning summary
BASE_NAME = "dataset2_cleaned_iter3"

save_cleaned_outputs(
    clean_df=df_clean,
    changes=cleaning_changes,
    out_dir=CLEANED_DIR,
    base_name=BASE_NAME,
)

# For convenience, show final paths
# clean_csv_path = os.path.join(CLEANED_DIR, f"{BASE_NAME}.csv")
clean_parquet_path = os.path.join(CLEANED_DIR, f"{BASE_NAME}.parquet")
clean_json_path = os.path.join(CLEANED_DIR, f"{BASE_NAME}_cleaning_changes.json")

print("\nFinal outputs:")
# print("  Clean CSV   :", clean_csv_path)
print("  Clean Parquet:", clean_parquet_path)
print("  Summary JSON :", clean_json_path)

[ok] Saved cleaned dataset to: c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\iteration_3\results\cleaned\dataset2_cleaned_iter3.csv
[ok] Saved cleaning summary to: c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\iteration_3\results\cleaned\dataset2_cleaned_iter3_cleaning_changes.json

Final outputs:
  Clean Parquet: c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\iteration_3\results\cleaned\dataset2_cleaned_iter3.parquet
  Summary JSON : c:\Users\joan\Desktop\FEINA\UPF\Course\Fourth_year\Primer_Trimestre\Project_Management\AB\AB_DataChallenge.Team102D\iteration_3\results\cleaned\dataset2_cleaned_iter3_cleaning_changes.json

## Quick descriptive stats (for documentation)

The cell below computes a few basic statistics useful for the Iteration 3 report:
- number of rows / columns after cleaning
- anomaly label distribution (if available)
- negative / zero consumption counts

In [8]:
print("Cleaned dataset shape:", df_clean.shape)

# Try to find anomaly-related columns
anom_cols = [c for c in df_clean.columns if "anom" in c.lower()]
print("Anomaly-related columns:", anom_cols)

if anom_cols:
    print("\nValue counts for first anomaly column:")
    display(df_clean[anom_cols[0]].value_counts(dropna=False).head(20))

for col in ["flag_negative_consumption", "flag_zero_consumption",
            "flag_anom_32768", "flag_anom_163840"]:
    if col in df_clean.columns:
        print(f"{col}: {df_clean[col].sum()} rows True")

Cleaned dataset shape: (21195970, 11)
Anomaly-related columns: ['CODI_ANOMALIA', 'flag_anom_32768', 'flag_anom_163840']

Value counts for first anomaly column:

CODI_ANOMALIA
163840     9784539
32768      6756239
1052800    1957770
33024       923983
256         626619
164096      336957
8192        193075
167936      157049
2           149888
262144      113977
131072       40680
272          26020
1050752      24196
4            19499
36864        18572
4224         17584
0            10748
133120        8784
2048          8784
16            7894
Name: count, dtype: int64

flag_anom_32768: 6756239 rows True
flag_anom_163840: 9784539 rows True